Repository sopt-makers/sopt-auth-frontend, pull requests merged in 2025-08, with the labels that each got.

#37 feat: 클라우드 플레어 pages fucntion 이슈로 빌드 outDir명 accounts로 변경
  .gitignore
  vite.config.ts
Labels: size/XS

#38 [HOTFIX] 클라우드 플레어 정적 자원 로드 이슈로 redirect 설정
  .gitignore
  public/_redirects
  vite.config.ts
Labels: size/XS

#41 feat: 모바일 반응형 수정
  index.html
  src/components/common/AuthSection.tsx
  src/components/common/Step.tsx
  src/routes/sign-up/auth/index.tsx
Labels: size/L

#43 feat: 리다이렉트 로직 추가
  src/api/postLogin.ts
  src/hooks/useLogin.ts
Labels: size/S

#45 feat: QA 반영 [ 전화 번호 인증 화면 / 소셜계정 재설정 / 바텀 시트 - 카카오톡 채널 로직 ]
  src/api/postAuthPhone.ts
  src/api/postVerifyPhone.ts
  src/components/common/AuthSection.tsx
  src/components/common/CannotLoginModal.tsx
  src/components/login-error/ReLoginSection.tsx
  src/hooks/useLogin.ts
  src/routes/__root.tsx
  src/routes/login-error/index.tsx
  src/utils/formatter.ts
  src/utils/validator.ts
  src/vite-env.d.ts
Labels: size/L

#47 feat: QA 반영 [바텀 시트 - 로그인했던 계정을 알고 싶어요 네비게이트 처리]
  src/api/constants/apiUrl.ts
  src/api/getSocialAccountsPlatfrom.ts
  src/api/postAuthPhone.ts
  src/api/postVerifyPhone.ts
  src/components/common/AuthSection.tsx
  src/components/common/CannotLoginModal.tsx
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/find-account/auth/index.tsx
Labels: size/L

#49 feat: QA - [구글 로그인 후 redirect path 변경]
  src/hooks/useLogin.ts
Labels: size/XS

#50 feat: QA - [소셜계정 변경 http method 변경]
  src/api/postUpadateSocialAccount.ts
  src/hooks/useUpdateSocialAccount.ts
Labels: size/S
