Repository sopt-makers/sopt-auth-frontend, pull requests merged in 2025-02, with the labels that each got.

#21 feat: 번호 인증 검사 API를 연동합니다.
  src/api/postVerifyPhone.ts
  src/components/common/AuthSection.tsx
Labels: size/M

#19 feat: 로그인 API를 연동합니다.
  package.json
  src/api/client.ts
  src/api/constants/apiUrl.ts
  src/api/postLogin.ts
  src/components/main/LastLoggedInBanner.tsx
  src/components/main/LoginSection.tsx
  src/hooks/useLogin.ts
  src/routeTree.gen.ts
  src/routes/auth/apple/callback/.gitkeep
  src/routes/auth/google/callback/index.tsx
  src/utils/formatter.ts
  src/utils/google.ts
  src/utils/nonce.ts
  src/vite-env.d.ts
  yarn.lock
Labels: size/L

#24 fix: 회원인증 페이지 layout shift 이슈를 해결합니다.
  src/components/common/AuthSection.tsx
Labels: size/S
